/**
 * compile-class.js — Compile .class.json schema-defined classes to JavaScript ES modules
 *
 * Generates proper ES modules with private fields, static members, accessors, etc.
 * from a JSON Schema 2020-12 class definition.
 */

/**
 * Compile a .class.json schema to a JavaScript ES module string.
 *
 * @param {object} classDef - Parsed .class.json content (must have $prototype: "Class")
 * @param {object} [opts]
 * @returns {string} JavaScript module source code
 */
export function compileClassJson(classDef, opts = {}) {
  const className = classDef.title;
  if (!className) throw new Error("compileClassJson: missing title (class name)");

  const baseClass = resolveBaseClass(classDef.extends);
  const fields = classDef.$defs?.fields ?? {};
  const ctor = classDef.$defs?.constructor;
  const methods = classDef.$defs?.methods ?? {};

  const lines = [];
  lines.push("// Generated by @jsonsx/compiler from .class.json — do not edit manually");
  if (classDef.$id) lines.push(`// Source: ${classDef.$id}`);
  lines.push("");

  // Class declaration
  const extendsClause = baseClass !== "Object" ? ` extends ${baseClass}` : "";
  lines.push(`class ${className}${extendsClause} {`);

  // Static fields
  for (const [key, field] of Object.entries(fields)) {
    if (field.scope !== "static") continue;
    const name = field.identifier ?? key;
    const prefix = field.access === "private" ? "#" : "";
    const initVal = field.initializer !== undefined
      ? JSON.stringify(field.initializer)
      : field.default !== undefined
        ? JSON.stringify(field.default)
        : "null";
    lines.push(`  static ${prefix}${name} = ${initVal};`);
  }

  // Instance field declarations (private)
  for (const [key, field] of Object.entries(fields)) {
    if (field.scope === "static") continue;
    if (field.access !== "private") continue;
    const name = field.identifier ?? key;
    lines.push(`  #${name};`);
  }

  if (Object.keys(fields).length > 0) lines.push("");

  // Constructor
  lines.push("  constructor(config = {}) {");
  if (ctor?.superCall || baseClass !== "Object") {
    const superArgs = ctor?.superCall?.arguments
      ? ctor.superCall.arguments.join(", ")
      : "";
    lines.push(`    super(${superArgs});`);
  }

  // Initialize instance fields from config or defaults
  for (const [key, field] of Object.entries(fields)) {
    if (field.scope === "static") continue;
    const name = field.identifier ?? key;
    const prefix = field.access === "private" ? "#" : "";
    const initVal = field.initializer !== undefined
      ? JSON.stringify(field.initializer)
      : field.default !== undefined
        ? JSON.stringify(field.default)
        : "null";
    lines.push(`    this.${prefix}${name} = config.${name} !== undefined ? config.${name} : ${initVal};`);
  }

  // Constructor body statements
  if (ctor?.body) {
    const bodyLines = Array.isArray(ctor.body) ? ctor.body : [ctor.body];
    for (const line of bodyLines) {
      lines.push(`    ${line}`);
    }
  }
  lines.push("  }");

  // Methods
  for (const [key, method] of Object.entries(methods)) {
    const name = method.identifier ?? key;
    const isStatic = method.scope === "static";
    const isPrivate = method.access === "private";
    const prefix = isPrivate ? "#" : "";
    const staticPrefix = isStatic ? "static " : "";
    const asyncPrefix = method.returnType?.$ref?.includes("Promise") || isMethodAsync(method) ? "async " : "";

    const params = resolveParams(method.parameters ?? []);
    const bodyStr = resolveBody(method.body);

    lines.push("");

    if (method.role === "accessor") {
      // Getter
      if (method.getter) {
        lines.push(`  ${staticPrefix}get ${prefix}${name}() {`);
        lines.push(`    ${method.getter.body}`);
        lines.push("  }");
      }
      // Setter
      if (method.setter) {
        const setterParams = resolveParams(method.setter.parameters ?? []);
        lines.push(`  ${staticPrefix}set ${prefix}${name}(${setterParams}) {`);
        lines.push(`    ${method.setter.body}`);
        lines.push("  }");
      }
    } else {
      lines.push(`  ${staticPrefix}${asyncPrefix}${prefix}${name}(${params}) {`);
      for (const line of bodyStr) {
        lines.push(`    ${line}`);
      }
      lines.push("  }");
    }
  }

  lines.push("}");
  lines.push("");
  lines.push(`export { ${className} };`);
  lines.push(`export default ${className};`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Resolve the base class name from an extends value.
 */
function resolveBaseClass(ext) {
  if (!ext) return "Object";
  if (typeof ext === "string") return ext;
  // { $ref: "./Parent.class.json" } — extract title from filename as best guess
  if (ext.$ref) {
    const ref = ext.$ref;
    const match = ref.match(/([A-Za-z0-9_]+)\.class\.json/);
    return match ? match[1] : "Object";
  }
  return "Object";
}

/**
 * Resolve parameter names from $ref or inline definitions.
 */
function resolveParams(params) {
  return params.map((p) => {
    if (p.$ref) return p.$ref.split("/").pop();
    return p.identifier ?? p.name ?? "arg";
  }).join(", ");
}

/**
 * Resolve body from string or array of strings.
 */
function resolveBody(body) {
  if (!body) return [""];
  if (Array.isArray(body)) return body;
  return [body];
}

/**
 * Simple heuristic: does the method body contain await?
 */
function isMethodAsync(method) {
  const body = Array.isArray(method.body) ? method.body.join("\n") : (method.body ?? "");
  return body.includes("await ");
}
